### ISSUE TITLE
misbehavior at netif.tmpl for vlan trunks

### ISSUE THREAD

**Issue by Mr-Pi** [funtoo/corenetwork#4]
For more information see [this comment](https://github.com/funtoo/corenetwork/commit/2707b21c03bb5b0d374ad2df32bae095eb475308) .

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-3562

**Comment by danielrobbins** [comment]
Great minds think alike. I independently added a very similar fix to the one you proposed in this commit. I did not support "net.${trunk}" since we never supported that option. You need either "netif.$trunk" or "$trunk" existing in /etc/init.d.
